4DModeller/fdmr

.github/workflows/check-standard.yaml
DESCRIPTION

Add INLA install and extra repo to setup-r

Adding INLA to desc, extra repo to setup-r

---

.github/workflows/check-standard.yaml

Removing Windows runner for now, see #49.

Remove windows GHA runner for now

---

DESCRIPTION
man/retrieve_tutorial_data.Rd
vignettes/covid_ST_mcmc.Rmd

Hi Gareth,
This is a request for merging a new COVID-19 tutorial for space-time BHM using MCMC method.
Thanks,
Xueqing

New COVID tutorial for space-time BHM using MCMC

---

vignettes/covid_mcmc.Rmd

This tidies the MCMC tutorial to update some link handling and variable names.

Tidy MCMC tutorial

---

DESCRIPTION
R/model_parse.R
R/shiny_priors.R

Move the model to run asynchronously.

Iss54+/async

---

.github/workflows/check-standard.yaml
.github/workflows/pkgdown.yaml
DESCRIPTION

Fix for `pak` error in GHA

---

_pkgdown.yml

I'd written `test` instead of `text` in the list of tutorials in the pkgdown yaml.

Correct test -> text in tutorial names

---

R/util_log.R

* **Summary of changes**
This adds the logging function required by the priors Shiny app.

Add logging code

---

CHANGELOG.md
R/model_parse.R
vignettes/priors.Rmd

Small change to read sd instead of mean during parsing of model output.

Fix read of sd from model output

---

vignettes/covid_mcmc.Rmd

To provide some interpretation on the different modelling performance / results of the MCMC-BYM, INLA-BYM and INLA-SPDE approaches in covid_mcmc.Rmd.

Provide some interpretation on the different performance of MCMC and INLA

---

CHANGELOG.md
DESCRIPTION
vignettes/data_preprocessing.Rmd
vignettes/hydro.Rmd
vignettes/mapping.Rmd

Removes the use of `rgdal` to use `sf` functions.

Remove use of `rgdal`

---

README.md
vignettes/DecisionTree.Rmd
vignettes/inlaFAQ.Rmd

added descriptions that are more meaningful about what 4d-modeller does for the occasional person browsing the website.

Update main page description

---

vignettes/Simulation_GaussianDat.Rmd

This is to create a tutorial that covers simulating Gaussian data, fitting the BHM and exploring the key functionality in fdmr.

A tutorial using simulated Gaussian data

---

vignettes/Simulation_PoissonDat.Rmd

Hi @gareth-j and @mnky9800n, this is to create an end to end tutorial using simulated Poisson data and ensure key functionality is covered.

End to end tutorial using simulated Poisson data

---

R/shiny_priors.R

Update the parameter names / labels on the left side of Shiny App to ensure their consistency with help descriptions.
Update help descriptions for spatial, fields and temporal priors to improve clarify.

Update the parameter labels and help descriptions for Shiny app

---

R/shiny_priors.R

Add some explanations about the descriptions of the variables and how altering the prior parameters impacts the priors in the help section.

Add an explanation in the help section for each slider bar.

---

vignettes/hydro.Rmd
vignettes/simulation_gaussian_data.Rmd

Small fix to hydrology tutorial for incorrect variable being passed to `group` argument in INLA model.

Fix to inla call to set group variable correctly

---

CHANGELOG.md
R/shiny_priors.R

This adds the formula to the code tab in the model builder app, it also fixes a bug I found when trying to make a map without having run the model.

Add formula to code output tab, added fix for bug on map creation

---

R/shiny_priors.R

Fixes a missing bracket and quotation marks in the code output of the model builder app.

Fix for model builder code output

---

CHANGELOG.md
R/shiny_priors.R

Clear button now clears f() box in model builder app

Clear button now clears f() box in model builder app

---

CHANGELOG.md
R/shiny_priors.R

This ensures the `time_variable` is actually a column name in the measurement data given to the model builder app.

Check if time_variable is a column name in `modelbuilder`

---

R/shiny_modelbuilder.R

This is to add some text to the tooltip strings for each prior

Add some text to the tooltip strings

---

CHANGELOG.md
R/plot_mapping.R

Add reverse option and raster legend for plot_mapping.R

---

vignettes/modelbuilder.Rmd

Add model builder vignette that was deleted

Add model builder vignette that was deleted

---

vignettes/hydro.Rmd

Call `fdmr::plot_mesh` function

Fix hydro mesh plot call

---

CHANGELOG.md
DESCRIPTION
R/plot_mapping.R
R/plot_mesh.R
R/shiny_meshbuilder.R
R/shiny_modelbuilder.R

Adds coordinates header and measurement tool to plotting functions and Shiny app maps

Show coordinates in spatial plots

---

CHANGELOG.md
DESCRIPTION

We were missing the `future` and `bsicons` packages from the `DESCRIPTION` file.

Add missing libraries to DESC

---

README.md

Added the contributor info from #258 to the README

Update README.md to have contributor guidelines

---

vignettes/data_loading.Rmd

This tutorial covers how to load netCDF and raster data into R.

Add a data loading tutorial

---

R/fit_model.R

adds the full formula creator for bru function

added full formula creator

---

CHANGELOG.md
R/shiny_meshbuilder.R
vignettes/meshbuilder.Rmd
vignettes/simulation_poisson_data.Rmd
vignettes/using_mapview.Rmd

This updates the `mesh_builder` app to allow the use of UTM data. I've changed from using `leaflet` to using [`mapview`](https://r-spatial.github.io/mapview/) which handles things easily.

Update maps to be more flexible and allow use of UTM coords

---

vignettes/decision_tree.Rmd

Removed the requested section from `decision_tree` tutorial.

Removed the `Comparing the output` section in `decision_tree.Rmd`

---

CHANGELOG.md
R/shiny_modelviewer.R

Added plot explainer text to the help tab of `model_viewer`

Added explainer text for the plots

---

vignettes/simulation_gaussian_data.Rmd

Removes a reference to the removed mesh checking function.

Remove reference to check mesh
